---
sidebar: sidebar 
permalink: task_deployment_validation_partners_resellers.html 
keywords: review, alerts, warnings, failed, rules, alerts, history, remediate, remediation, suppress, display, fail, warning, pass, notifications, email 
summary: 파트너 또는 리셀러로서 클라이언트 인프라의 배포를 검증할 수 있습니다. 
---
= 파트너 및 리셀러를 위한 배포를 검증합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
파트너 또는 리셀러는 대시보드에 표시되는 데이터를 검토하거나 상태 보고서를 생성하여 고객 인프라 구축을 확인할 수 있습니다.

.시작하기 전에
* 고객 사이트에 새 FlexPod를 설치했거나 기존 FlexPod를 사용하고 있습니다.
* FlexPod 장치에서 계정을 만들었습니다.
* TACACS+ 서버를 사용하는 경우 CSA 사용자 권한을 부여했습니다.
* 에이전트를 다운로드하고 설치했습니다.
+
을 참조하십시오 link:task_setup_deploy_agent.html["에이전트를 설정하고 배포합니다"].

* 에이전트에 대한 네트워킹을 설정하고 선택적으로 에이전트에 SSL 인증서를 설치했습니다.
* NetApp 자격 증명을 사용하여 고객이 포털에 인프라를 추가할 CI를 작성했습니다.
+
을 참조하십시오 link:task_add_infrastructure["포털에 인프라를 추가합니다"] CSA 포털에서 CI를 작성하려면

* 필요에 따라 다른 사용자와 인프라를 공유했습니다.


파트너와 리셀러는 고유한 NetApp 자격 증명을 사용하여 CSA 포털에 로그인하여 검증 프로세스를 시작합니다.

. 에 로그인합니다 https://csa.netapp.com/["Converged Systems Advisor 포털"^] NetApp 자격 증명을 사용합니다.
. [CI 선택]을 클릭한 다음 해당 고객의 해당 CI를 클릭하거나 검색 상자에 CI 이름을 입력합니다. CI에 대한 대시보드가 표시됩니다.


파트너 또는 리셀러는 다음 방법을 사용하여 고객의 인프라를 검증할 수 있습니다.

* 대시보드에서 인프라스트럭처의 다양한 측면을 확인할 수 있습니다.
+
** * 펌웨어 상호 운용성 * 은 설치된 소프트웨어 버전을 표시합니다. 자세한 내용을 보려면 각 제목을 클릭하십시오.
** * 지원 계약 * 은 계약이 만료되는 시점을 표시합니다. 자세한 내용을 보려면 * 세부 정보 보기 * 를 클릭하십시오.
** * 상담원 상태 * 는 모니터되는 장치를 포함하여 상담원에 대한 세부 정보를 표시합니다.
** * 용량 * 은 디스크 공간, 네트워크 포트 및 UCS 블레이드 섀시의 활용률을 보여 줍니다. 각 활용도에 대한 세부 정보를 보려면 링크를 클릭하십시오.
** * 상태 * 는 인프라의 스토리지, 컴퓨팅, 네트워크 및 가상화 기능에 대한 규칙의 상태를 그래픽으로 표시합니다. 추가 세부 정보를 보려면 그래픽의 색상 영역을 클릭합니다.
** * 규칙 요약 * 은 실패한 규칙 및 경고에 대한 경고를 표시합니다. 각 행의 왼쪽에 있는 화살표를 클릭하거나 장치 이름을 클릭하여 추가 세부 정보를 봅니다.


* 작업 표시줄에서 * 보고서 -> 상태 보고서 * 를 선택하여 자세한 통합 시스템 상태 보고서를 생성합니다. 브라우저에서 보거나 PDF 파일로 다운로드하거나 이메일로 공유할 수 있습니다.

